name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: [docker]
    container:
      image: ${{ vars.REGISTRY_HOST }}/${{ vars.REGISTRY_IMAGE }}
    env:
      REGISTRY_HOST: ${{ vars.REGISTRY_HOST }}
      REGISTRY_IMAGE: ${{ vars.REGISTRY_IMAGE }}
      APP_NAME: ${{ vars.APP_NAME || 'conan' }}

    steps:
      - name: Validate required variables
        run: |
          if [ -z "${{ vars.REGISTRY_HOST }}" ]; then
            echo "ERROR: REGISTRY_HOST variable is not set"
            exit 1
          fi
          if [ -z "${{ vars.REGISTRY_IMAGE }}" ]; then
            echo "ERROR: REGISTRY_IMAGE variable is not set"
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host
          config-inline: |
            [registry."${{ vars.REGISTRY_HOST }}"]
              http = true
              insecure = true

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ vars.REGISTRY_HOST }}/${{ env.APP_NAME }}:latest
          provenance: false
          cache-from: type=registry,ref=${{ vars.REGISTRY_HOST }}/${{ env.APP_NAME }}:buildcache
          cache-to: type=registry,ref=${{ vars.REGISTRY_HOST }}/${{ env.APP_NAME }}:buildcache,mode=max

      - name: Notify deployment success
        if: success()
        run: echo "Docker image built and pushed successfully!"
